### ISSUE TITLE
Defamatory statement in README

### ISSUE THREAD

**Issue by plougher** [AgentD/squashfs-tools-ng#10]
The following comments in the README are defamatory to me, Phillip Lougher. 

"The filesystem itself and the user space tooling were originally developed by
Phillip Lougher with third party contributions that have accumulated over time.

Unfortunately, the original user space tooling does not support a lot of
standard use cases, the source code of the tools is in a pretty deteriorated
state and apparently no longer maintained."

If they are  not removed, I will report this project to GitHub

**Comment by AgentD** [comment]
Hi!

I wasn't aware that squashfs-tools development was moved to github. All I was aware off for the past years were the SF site & repo that down stream distros also still point to, the mailing list which I've been following and the commit history of the kernel.

Anyway, my comment about upstream development being dead is thus *objectively false* and I must retract that.

As for the rest of the comment, I tried to tone it down a bit and rephrased it to express more obviously that I'm stating my own personal opinion and motives behind starting this project.

> "The filesystem itself and the user space tooling were originally developed by
> Phillip Lougher with third party contributions that have accumulated over time.
I thought that it would only be fair to give you credit, but since you included it in the parts you don't like, I removed that for now.

Greetings,

David
