### ISSUE TITLE
loading filesystem tree: location out of bounds.

### ISSUE THREAD

**Issue by josch** [AgentD/squashfs-tools-ng#22]
Steps to reproduce:

```
$ mkdir foo
$ touch foo/bar
$ tar -C ./foo -c . > out.tar
$ tar tf out.tar
./
./bar
$ tar2sqfs rootfs.sqfs < out.tar
[...]
$ sqfs2tar rootfs.sqfs > out.tar
rootfs.sqfs: loading filesystem tree: location out of bounds.
```

**Comment by AgentD** [comment]
The problem is two fold:
 - `tar2sqfs` sanitizes the path names, i.e. it turns `./bar` into `bar` but turns `./` into an empty string.
 - libsquashfs does not check and happily tries to add an entry with an empty string.
   - The SquashFS format stores directory entries with the length count off-by-one, assuming that     zero length strings don't occour.
   - The resulting length libsquashfs stores is interpreted as a huge number by the reader.
   - The libsquashfs reader catches this when and `sqfs2tar` fails.

My proposed solution for this is as follows:
 - Add a check to `tar2sqfs` that skips entries if the sanitized name is empty string
   - Issue a warning for this or abort unless it is a *directory* named `./`
   - TODO: Add a new flag in a future version to use the permissions, etc... from `./` for the root node? Perhaps a more generic handle "cut off prefix X and turn X into the root node"?
 - Add a check to `sqfs_dir_writer_add_entry` to throw an error if an empty string as supplied as an entry name.

Which is implemented by commits 018e0e0a8e3c36a6bedf60eedeb8262311d90869 and 063f57dec14986d1895d83d9113fd1dec7f135f4.
