### ISSUE TITLE
Switch for detecting compression format per block

### ISSUE THREAD

**Issue by XVilka** [AgentD/squashfs-tools-ng#26]
See for example https://github.com/mncoppola/rpef/blob/master/utilities_src/unsquashfs-1.3.c#L176

Some tools can use different compression algorithms from what defined by superblock and can contain multiple compression formats in one image.

See also https://github.com/devttys0/sasquatch/ patchset for more information on various different SquashFS compression configurations.

**Comment by AgentD** [comment]
The modular nature of the libsquashfs compressor interface should make it easy to implement custom compressors, including ones that try brute-force decompressing with other compressors.

A while back, I pieced together such a thing for a small forensics tool. I should dig that up again and port it to the current state. A sasquatch-like forensic tool could definitely make use of that.

A generic way to detect what compressor was used might not be that easily possible, since not all of them store obvious headers (e.g. LZO).

**Comment by AgentD** [comment]
Closed in favour of #55
